insert into settings (key, value, description)
values  ('WRK_HTTP_TIMEOUT_MS', '10000', 'Timeout used during http checks'),
        ('WRK_GOROUTINES', '30', 'number of goroutines to start for each worker'),
        ('WRK_THROTTLE_RPS', '100', 'limit the number of request that each worker performs every second'),
        ('WRK_BUF_CH_SIZE', '100', 'size of buffered channel used to pass requests from the queue to the goroutines'),
        ('WRK_GRACE_PERIOD_MS', '10000', 'time since last request processed that each go routine wait before stopping. Used for gracefully stopping the application'),
        ('WRK_WRKS_READY_TIMEOUT_MS', '15000', 'time for all the goroutines started to be ready to work'),
        ('WRK_HTTP_USER_AGENT', 'Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148', 'user agent used during HTTP requests'),
        ('QUEUE_PREFETCH_COUNT', '100', 'number of messages to consume each request'),
        ('QUEUENAME_REQUEST', 'brainypingqueue', 'queue name used for sending/receiving checks requests'),
        ('QUEUENAME_RESPONSE', 'brainypingresponsequeue', 'queue name used for sending/receiving processed checks responses '),
        ('BL_OWNERUID', 'BL-OWNERUID', 'user id of the owner of the check loaded during a bulk load'),
        ('BL_BULK_SAVE_SIZE', '1000', 'number of records to include in each saving operation'),
        ('RC_BUF_CH_SIZE', '100', 'size of the buffered channel used to pass responses from the queue consumer to the response collector process'),
        ('RC_GRACE_PERIOD_MS', '5000', 'time to wait before closing the application to make sure all buffered responses are saved'),
        ('RC_BULK_SAVE_SIZE', '100', 'number of records to include in each saving operation'),
        ('RC_SAVE_AUTO_FLUSH_MS', '10000', 'max time waited before buffered responses are saved even if the limit is not reached. This is to avoid having records only staged in memory for too long'),
        ('STM_SAVE_AUTO_FLUSH_MS', '5000', 'status monitor max wait between flushing the buffer to db'),
        ('RR_DAYS', '7', 'retention period for responses collection records'),
        ('RR_FREQUENCY_SEC', '900', 'responses retention frequency'),
        ('RR_BATCH_SIZE', '1000', 'limit the number of responses to be deleted in each db operation. Multiple operations will be executed until retention period is satisfied.');