#
# RABBITMQ AND MYSQL FOR DEV PURPOSE
#

version: '3.3'

services:

  rabbitmq3:
    image: rabbitmq:3.9-management
    hostname: myrabbithost
    container_name: myrabbit
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    volumes:
      - '~/.dockerdata/brainyping/rabbitmq/data:/var/lib/rabbitmq'
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - '~/.dockerdata/brainyping/mysql/data:/var/lib/mysql'
    ports:
      - '3306:3306'
