BINARY_FOLDER="./bin"

build:
	GOOS=darwin GOARCH=arm64 go build -o ${BINARY_FOLDER}/darwin_arm64/ -v ./...
	GOOS=linux  GOARCH=amd64 go build -o ${BINARY_FOLDER}/linux_amd64/ -v ./...
	GOOS=linux  GOARCH=arm64 go build -o ${BINARY_FOLDER}/linux_arm64/ -v ./...

